version: '3.9'
services:
  mem0_service:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-8050}:8050"
    depends_on:
      - db
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mem0
    ports:
      - "5432:5432"
